### ISSUE TITLE
ListOptions don't work when listing Images

### ISSUE THREAD

**Issue by Dzhuneyt** [dlombard/digitalocean_dart#3]
Use case:
```dart
this.imagesService = new ImageService(widget.digitaloceanClient);
this.imagesService.list(ListOptions(1, perPage: 100)).then((value) {
      print(value.images.length);
    });
```

Expected result: Printed a length of 100 images
Current result: Printed a length of 20 images

After some debugging and breakpoints, I pinpointed the issue to the `/lib/src/models/listOptions.dart` file, and more specifically - whenever the list() method calls `Utils.getPathFromListOptions()` internally, that in turn calls the `toString()` method of the `ListOptions` class, which finally generates a value like `/v2/images?1&100` in the end, instead of a correct value of `/v2/images?page=1&per_page=100`.

**Comment by dlombard** [comment]
Hey good catch. 

I've just updated the code. The tests are conclusive. Let me know if everything works on your end.
